#!/bin/bash

ssr_main() {
  case $1 in 
  start) ssr_start ;;
  stop)  ssr_stop ;;
  git)   ssr_git ;;
  ungit) ssr_ungit ;;
  *)     ssr_help ;;
  esac	
}

ssr_help() {

	echo "no help!  try again!"
}

ssr_start() {
  echo "ssr starting... "
  ssr restart
  if [ $? -eq 0 ]; then
     echo "ssr start successfully!"
  else
     echo "ssr start failed!"
  fi
 
  echo "startting  provixy..."
  /etc/init.d/privoxy start
  if [ $? -eq 0 ];  then
    echo  "proxy agent started!"
  else
    echo "proxy agent start failed!"
  fi 
  
  echo "setting http_proxy/https_proxy..."
  sed -i '108c export http_proxy=http://127.0.0.1:8118' ~/.zshrc
  sed -i '109c export https_proxy=http://127.0.0.1:8118' ~/.zshrc
  export http_proxy=http://127.0.0.1:8118
  export http_proxy=http://127.0.0.1:8118
  echo "set http proxy  success. test connect to  google.com..."
  curl www.google.com >> ~/.ssp_log
  if [ $? -eq 0 ]; then 
     echo "connnect success!"
  else
     echo "connect failed!"
  fi     
  
}

ssr_stop() {
  echo "ssr stopping... "
  ssr stop
  if [ $? -eq 0 ]; then
     echo "ssr stop successfully!"
  else
     echo "ssr stop failed!"
  fi

  echo "stopping  provixy..."
  /etc/init.d/privoxy stop
  if [ $? -eq 0 ];  then
    echo  "proxy agent stoped!"
  else
    echo "proxy agent stop failed!"
  fi

  echo "unsetting http_proxy/https_proxy..."
  sed -i '108c unset http_proxy' ~/.zshrc
  sed -i '109c unset https_proxy' ~/.zshrc
  unset http_proxy
  unset https_proxy
  echo "set http proxy success. test connect to  baidu.com..."
  curl www.baidu.com >> ~/.ssp_log
  if [ $? -eq 0 ]; then
     echo "connnect success!"
  else
     echo "connect failed!"
  fi
}

ssr_git() {

  echo "setting git proxy..."
  git config --global https.proxy 'http://127.0.0.1:8118'
  git config --global http.proxy  'http://127.0.0.1:8118'
  echo "setting git proxy success."
  git config --global --get http.proxy
  git config --global --get https.proxy
}

ssr_ungit() {

  echo "unsetting git proxy..."
  git config --global --unset http.proxy
  git config --global --unset https.proxy
  echo "unsetting git proxy success."
  git config --global --get http.proxy
  git config --global --get https.proxy
}

ssr_main $1
